# Site settings
title: OpenDDS
email: mesnierp@objectcomputing.com
description: OpenDDS is an open source C++ implementation of the Object Management Group (OMG) Data Distribution Service (DDS). OpenDDS also supports Java bindings through JNI.
twitter_username: ObjectComputing
github_username:  pmesnier

theme: minima

# github-metadata
repository: objectcomputing/OpenDDS
gems: ['jekyll-github-metadata', 'jekyll-redirect-from']

